baseurl: "https://meta.宙.space/"
title: "元宇宙"
theme: "zen"
languageCode: "en-GB"       # Set your language code (only needed for none multilingual sites).
pluralizeListTitles: false
menu:
  main:
  - identifier: home
    name: 主页
    title: home section
    url: /
    weight: 9
  - identifier: gallery
    name: 无形
    title: gallery section
    url: /gallery/
    weight: 10
  - identifier: podcast
    name: 希声
    title: podcast section
    url: /podcast/
    weight: 30
  - identifier: blog
    name: 至简
    title: blog section
    url: /blog/
    weight: 20
  - identifier: about section
    name: 关于
    title: about
    url: /about/
    weight: 60

params:
  cookieConsent: true       # Show cookie consent form, default false.
  contact: "zen@宙.space"
  dateformat: ""            # Set the date format, default to "2 January, 2006"
  description: ""           # Set site description, used in meta tags and JSON-LD
  #favicon: ""               # Relative path to favicon in json feed, no leading slash.
  feedlinks: true           # Show feed links in the footer.
  footer: 
  icon: ""                  # Relative path to icon in json feed and JSON-LD, no leading slash.
  image: ""                 # Relative path to site image in JSON-LD, no leading slash.
  imageMaxWidth: ""         # Max width for images added via figure shortcode.
  jquery: true              # Add jQuery
  languageDir: ""           # Set ltr or rtl, defaults to ltr.
  logo: on                  # Turn off the logo.
  mainSections:             # The sections you want to have listed on the front page.
    - "gallery"             # Default to the section with most content if not set.
    - "blog"                # Set to empty if no section should be listed.
    - "podcast"             # Set to empty if no section should be listed.
  microUsername: "7enchan"         # Your micro.blog username.
  mobileMenu: true          # Turn on a mobile menu on small screens.
  piwikSiteId:              # Matamo site id
  piwikTrackerUrl: ""       # Matamo url, schemaless and no slash on end (example.org/matamo).
  poweredby: true           # Show powered by hugo in footer
  privacyPolicyUrl: ""      # If set will add link to cookie consent form.
  realfavicongenerator:     # If full set of favicons, site manifest etc. exists, default false.
  relatedposts: true        # Show related posts under a "See also" section, default false.
  searchLimit: 20           # Max number of search hits, default 20.
  sidebar: false             # Show a sidebar to the right
  submitted: true           # Show author and date information for a post.
  themeColor:               # Hex color value, used in meta tags, default "#ffffff".
  
podcast:
    title:                  # * Feed title, defaults to site title (iTunes).
    description:            # * Feed description/summary, defaults to  site description (iTunes).
    image:                  # * Feed image, place inside assets directory (iTunes).
    category:
      name:                 # * Feed category (iTunes).
      subcategories: []     # Feed sub category (iTunes).
    explicit: false/true    # Feed explicit settting, default to false (iTunes).
    author:                 # Feed author (iTunes).
    owner:
      name:                 # Feed owner name (iTunes).
      email:                # Feed owner e-mail (iTunes).
    lang:                   # Feed language, defaults to site language (iTunes).
    block: no/yes           # Block the feed from iTunes, default to no (iTunes).
    complete: no/yes        # Set the feed as complete, defaults to no (iTunes).
    type: episodic/serial   # Podcast type, defaults to episodic (iTunes).
    newfeed:                # Are you moving? Set the new feed url here (iTunes).
    cdn:                    # CDN url, no slash on end (https://cdn.example.org).
    local: true            # Are the audio files local (true) or remote (false), default to true.
    preload: none/metadata/auto # Set on the HTML5 audio tag, defaults to "metadata".

